name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Se activa al hacer push en tu rama actual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy and Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/Gestion-de-Servicios
            git pull origin build
            npm install
            npm run build
            pm2 restart lobia-web